# Generated by Django 4.2.4 on 2024-05-17 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaketLangganan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_paket', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resolusi_layar', models.CharField(max_length=100)),
                ('dukungan_perangkat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiLangganan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_awal', models.DateField()),
                ('tanggal_akhir', models.DateField()),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='langganan.paketlangganan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_dimulai', models.DateField()),
                ('tanggal_akhir', models.DateField()),
                ('metode_pembayaran', models.CharField(max_length=100)),
                ('tanggal_pembayaran', models.DateField()),
                ('total_pembayaran', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='langganan.paketlangganan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
